business_names:
  - 10 Barrel
  - 13th St. Pub & Grill
  - Acero
  - Albertsons
  - Albertsons - Vista
  - All Below
  - Anthonys
  - Asana Climbing Gym
  - Atlas Bar
  - Bardenay
  - Barbarian Brewing
  - Bar Gernika
  - Beehive Salon
  - Big City Coffee
  - Bittercreek
  - Boise Art Glass
  - Boise Art Museum
  - Boise Chambers Gift Shop
  - Boise Contemporary Theater
  - Boise Co-Op
  - Boise Fry/Waffle Me Up
  - Boise Juice Co
  - Boise Center
  - Broadway Bar
  - Broadway Music
  - Broadway on the Rocks
  - Burger Belly
  - Buy Idaho
  - Cactus Bar
  - Cafe Darte
  - Cafe Rio
  - Capital Gallery
  - Capital Cellars
  - Chalice Tattoo Studio
  - Chilis
  - Chip
  - Chocolate Bar
  - Cloud 9 Brewing
  - Co-Op Pet Store
  - Co-Op Wine Shop
  - Crazy Neighbors
  - Crooked Fence Brewing
  - Crones Cupboard
  - Das Alpenhaus Deli
  - Dawson Taylor
  - Double Tap Pub
  - Drake Cooper
  - Ecolounge Ski Shop
  - Edge Brewery
  - Emerald Lanes
  - Fantastic Games
  - Fanci Freeze
  - Food Land
  - Foster Building
  - Fred Meyer
  - Fluff Hardware
  - Flying M
  - Flying Pie
  - Gils K9
  - Goldys/Goldys Corner
  - Goldsteins Bagels
  - Grove Fitness Club and Spa
  - Guru Donuts
  - Hops and Bottles
  - Hampton Inn
  - HandleBar
  - Happy Hour
  - Hyde Perk Cafe
  - Idaho Mountain Touring IMT
  - Idaho State Museum
  - Idaho Trust
  - InkSlave Tattoo
  - Ink Spa Tattoo
  - Indy Clover
  - Iron Wolf Tattoo
  - JUMP
  - Janjou Bakery
  - Java
  - Java DT
  - Jersey Mikes
  - Jitters by Jayne
  - Jumpin Janets?
  - KIN
  - Kim Nails
  - Knitting Factory
  - Latah
  - Leku Ona
  - LemonTree
  - Liquid Laughs
  - Lost Grove Brewing
  - Lunatic Fringe
  - Main Street Deli
  - Mad Swede Brew Hall
  - Matlacks
  - Meriwether Cider
  - Modern Hotel
  - Modern Sound and Vynil
  - Muse Salon & Spa
  - Nampa
  - Nara Sushi
  - Neurolux
  - No New Vintage
  - OMichaels
  - Opera Idaho
  - Outdoor Exchange
  - Overland Bar
  - Parilla
  - Payette Brewing
  - Paddles Up Poke
  - Peace Valley Dry Goods
  - Pie Hole
  - Pizza Pie Cafe
  - Pita Pit
  - Prestige
  - Proletariat Wine Bar
  - Push & Pour
  - Push & Pour Coffee
  - Qdoba Mexican Grill
  - Quinns
  - Radio Boise
  - Record Exchange
  - Record World
  - Rediscovered Books
  - Reed Cycle
  - Resurrected Tattoo
  - R Gray Gallery
  - R Bar
  - Roots Zero Waste Market
  - Rustica
  - Safari Inn
  - Sakana Sushi
  - Second Chance Building Materials
  - Six Daggers Tattoo
  - Slow by Slow Coffee
  - Solid
  - St.Lawrence Gridiron
  - St.Vincent de Paul Thrift Center
  - Stellas Ice Cream
  - Suds
  - Taphouse
  - Tangos
  - The Balcony
  - The Commons Climbing Gym
  - The Egyptian Theater
  - The End Zone
  - The Flicks
  - The Funky Taco
  - The Grove Hotel
  - The High Note Cafe
  - The Mode Lounge
  - The Ram
  - The Shredder
  - The Stil
  - The VAC
  - The Whaler Tea
  - The Gym on 8th St.
  - Thistle & Poppy Hair Salon
  - Tin Roof Tacos
  - Tri Town Bicycles
  - Twin Peaks
  - Uptown Cheapskate
  - Vapor Loft
  - Vista Bar
  - Wok Inn Noodle
  - Wild Root
  - Wiseguys Pizza
  - Yoitomo Sushi
  - Zen Riot
  - Zees Rooftop Cafe

areas:
  - Bown Crossing
  - Bogus Basin
  - BoDo
  - Broadway
  - Downtown 4th to Capital
  - Downtown 9th to 15th
  - Downtown Capital to 9th
  - Garden City
  - Highway 21
  - Hyde Park
  - Latah
  - Nampa
  - Orchard
  - Park Center
  - State Street
  - State Street/SW Main
  - The Bench
  - Vista
