business_names:
  - Discovery Center of Idaho
  - Basque Center
  - Reef
  - Tom Graineys
  - Spacebar Arcade
  - Hannahs
  - The Flicks
  - Alchemist Coffee
  - Capital Cellars
  - Form & Function
  - Wylder
  - The High Note Cafe
  - Zees Rooftop Cafe
  - Whiskey Bar
  - Guidos
  - Sammys/Silly Birch
  - Flying M
  - Parilla
  - Dharma Sushi
  - Blue Sky Bagels
  - Chip
  - Rise & Grind
  - Buy Idaho
  - Pengillys Saloon
  - Wiseguys Pizza
  - Basque Market
  - Boise Brewing
  - The Front Door
  - Peace Valley Dry Goods
  - Java DT
  - Cactus Bar
  - Bar Gernika
  - Jimmy Johns
  - Beehive Salon
  - Leku Ona
  - Basque Museum
  - Bardenay
  - Ansots
  - Pie Hole
  - Dawson Taylor
  - Ward P. Hooper
  - Fluff Hardware
  - Stellas Ice Cream
  - Rediscovered Books
  - Fantastic Games
  - Cotopaxi
  - Chocolate Bar
  - City Peanut Shop
  - The Funky Taco
  - Trailhead Boise
  - Boise Center
  - The Balcony
  - JUMP
  - The Mode Lounge
  - Boise Contemporary Theater
  - KARMA
  - Idaho State Museum
  - Mad Swede Brew Hall
  - Ballet Idaho
  - Boise Co-Op
  - Co-Op Pet Store
  - Diablo & Sons
  - Bittercreek
  - Prost
  - Wild Root
  - Rustica
  - The Gym on 8th St.
  - St.Lawrence Gridiron
  - Taters Grove Plaz
  - Buffalo Wild Wings
  - Acero
  - Pho 208
  - Co-Op Wine Shop
  - Les Bois Wine
  - Space Banana
  - 10 Barrel
  - Alias Coffee Shop
  - Graeber & Co. Salon
  - Main Street Deli
  - McUs
  - Paddles Up Poke
  - Yen Ching
  - Banana Ink
  - Opera Idaho
  - Shift Boutique
  - Jitters by Jayne
  - Meriwether Cider
  - Nara Sushi
  - The Egyptian Theater
  - Century Link Arena
  - Taphouse
  - Boise Fry/Waffle Me Up
  - Boise Art Museum
  - Goldys/Goldys Corner
  - Press and Pony
  - Grove Fitness Club and Spa
  - Library!
  - The Grove Hotel
  - Mulligans
  - Iron Wolf Tattoo
  - 3Peat
  - Edge Brewery
  - The Olympic
  - District Coffeehouse
  - InkSlave Tattoo
  - LemonTree
  - Hyatt Place
  - Guru Donuts
  - 10th St Station
  - The Shredder
  - Neurolux
  - Linen Building
  - KIN
  - Boise Art Glass
  - dV8 Salon
  - Calle 75
  - Record Exchange
  - Prestige
  - Safari Inn
  - Barbarian Brewing
  - Radio Boise
  - Atlas Bar
  - Matlacks
  - Boise Chambers Gift Shop
  - Foot Dynamic
  - Manfreds
  - Woodland Empire Brewing
  - Anthonys
  - Modern Hotel
  - Broadcast Coffee
  - Shrine Social Club
  - Idaho Mountain Touring IMT
  - Hops and Bottles
  - Big City Coffee
  - Outdoor Exchange
  - Second Chance Building Materials
  - Crazy Neighbors
  - HandleBar
  - Dowdys Automotive
  - aTavola
  - Push & Pour
  - Albertsons - Vista
  - Food Land
  - Das Alpenhaus Deli
  - Bikes and Beans
  - Jumpin Janets?
  - Brewers Haven
  - Thistle & Poppy Hair Salon
  - Muse Salon & Spa
  - Ophidia
  - New Colony Brewing
  - Sakana Sushi
  - Modern Sound and Vynil
  - BBQ 4 Life
  - Red Bench Pizza
  - Primal Coffee
  - Chalice Tattoo Studio
  - The Stil
  - Crones Cupboard
  - Chaing Mai
  - Emerald Lanes
  - Quinns
  - Navajo Room
  - Wok Inn Noodle
  - Emerald Lanes
  - Stubbs Sports Bar
  - Fred Meyer
  - Home Depot
  - Zen Riot
  - The Commons Climbing Gym
  - Resurrected Tattoo
  - Mclearys Pub
  - Tangos
  - Lucianos
  - Overland Bar
  - Gastons Bakery
  - Twin Peaks
  - Johnnys Fitclub
  - Purple Lotus
  - Vista Bar
  - Boise Weekly
  - Kichii Sushi and Spirits
  - Cafe Darte
  - Liquid Laughs
  - Solid
  - Foster Building
  - Double Tap Pub
  - VOXN
  - Idaho Trust
  - Slow by Slow Coffee
  - Goldsteins Bagels
  - Drake Cooper
  - White Dog Brewing
  - Nomad
  - Gas Lantern
  - Warehouse
  - Knitting Factory
  - Boise Contemporary Theater
  - Idaho Shakespeare Festival Offices
  - Hap Hap Lounge
  - Treefort Music Hall
  - The Stil
  - Hampton Inn
  - Capital Gallery
  - Pi Baby
  - No New Vintage
  - R Gray Gallery
  - Lunatic Fringe
  - Studio Lotus
  - Nordic Knives
  - Ink Spa Tattoo
  - Sprout Design
  - Yoitomo Sushi
  - Lost Grove Brewing
  - MOD Pizza
  - Payette Brewing
  - Broadway on the Rocks
  - Yoga Six
  - Jims Alibi
  - Extreme Pizza
  - Pyramid Tattoo Company
  - Suds
  - The Ram
  - Broadway Music
  - Tin Roof Tacos
  - R Bar
  - Burger Belly
  - Pie Hole
  - Whole Foods
  - Broadway Bar
  - Flying Pie
  - Idaho Pizza Company
  - Record World
  - Pizza Pie Cafe
  - Pho Le
  - Jersey Mikes
  - The End Zone
  - Pita Pit
  - Devotion Tattoo and Piercing
  - Six Daggers Tattoo
  - Bairds Dry Cleaning
  - Courtyard by Marriott
  - Pure Barre
  - Qdoba Mexican Grill
  - All Below
  - Chilis
  - Cafe Rio
  - Uptown Cheapskate
  - Jamaca Me Tan
  - Vapor Loft
  - The Whaler Tea
  - Royal Cut
  - Hans Chimaek Korean Fried Chicken
  - St.Vincent de Paul Thrift Center
  - Roots Zero Waste Market
  - Push & Pour Coffee
  - The VAC
  - Somewhere Bar
  - Powderhaus
  - Berts Brewing
  - Coiled Wines
  - Meriwether Cider
  - Telaya
  - Crooked Fence Brewing
  - Asana Climbing Gym
  - Barrel House
  - Proletariat Wine Bar
  - Wepa
  - Black Moon Pizza
  - Barbarian Brewing
  - Reed Cycle
  - Lulus Pizza
  - OMichaels
  - Ecolounge Ski Shop
  - McUs
  - Highlands Hollow
  - Timber Coffee
  - Parilla
  - Northend Pizza
  - Tri Town Bicycles
  - Java
  - Joyride Cycles
  - Hyde Perk Cafe
  - Lost Grove Brewing
  - 13th St. Pub & Grill
  - Certified Coffee + Bakery
  - The Royal
  - Hollywood Yoga
  - Smoky Mountain Pizza
  - Albertsons
  - Dutch Bros
  - Fanci Freeze
  - Flying Pie
  - Mazzah
  - Kim Nails
  - Boise Juice Co
  - Westside Drive In
  - Cloud 9 Brewing
  - Janjou Bakery
  - Indy Clover
  - Good Times Bagels
  - The Capri
  - Gils K9

areas:
  - 4th-Capital
  - Capital-9th DT
  - 10th-15th DT
  - BoDo DT
  - Hyde Park
  - The Bench
  - State Street/SW Main
  - Garden City
  - Broadway
