# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end
# Clear existing data (use with caution in production)
puts 'Clearing existing data...'
User.destroy_all
puts 'Data cleared.'

# Seed Users
puts 'Creating users...'
users = [
  { first_name: 'Casey', last_name: 'Dahlgren', email: 'auggiedahlgren@gmail.com', password: '123456', role: :admin },
  { first_name: 'Jake', last_name: 'Dahlgren', email: 'jake.dahlgrendev@gmail.com', password: '123456', role: :admin },
  { first_name: 'Jim', last_name: 'Murray', email: 'moresun26@gmail.com', password: '123456', role: :user },
  { first_name: 'Wyatt', last_name: 'King', email: 'wnk0722@gmail.com', password: '123456', role: :user },
  { first_name: 'Tori', last_name: 'Thomas', email: 'tori.thomas0430@gmail.com', password: '123456', role: :user },
  { first_name: 'Madi', last_name: 'Warner', email: 'mpwarner94@gmail.com', password: '123456', role: :user },
  { first_name: 'Justin', last_name: 'Videen', email: 'videenjustin@gmail.com', password: '123456', role: :user }
]
users.each do |user|
  User.create!(user)
end
puts 'Users created.'

# seeds.rb

assignments = [
  ['riverside hotel', 'Wyatt', 'Garden City'],
  ['telaya', 'Wyatt', 'Garden City'],
  ['Barbarian GC', 'Wyatt', 'Garden City'],
  ['Flourish', 'Wyatt', 'Garden City'],
  ['Baldwin lock n key', 'Wyatt', 'Garden City'],
  ['Reuseum', 'Wyatt', 'Garden City'],
  ['Dogtopia', 'Wyatt', 'Garden City'],
  ['Western Collective', 'Wyatt', 'Garden City'],
  ["Bert's Brewing", 'Wyatt', 'Garden City'],
  ['Parcero', 'Wyatt', 'Garden City'],
  ['Split rail', 'Wyatt', 'Garden City'],
  ['Zion Art Glass', 'Wyatt', 'Garden City'],
  ['Roots market', 'Wyatt', 'Garden City'],
  ['Lit Room', 'Wyatt', 'Garden City'],
  ['PushPour GC', 'Wyatt', 'Garden City'],
  ['Wepa', 'Wyatt', 'Garden City'],
  ['Coiled', 'Wyatt', 'Garden City'],
  ['Black Moon', 'Wyatt', 'Garden City'],
  ['Section 37 Axe Throwing', 'Wyatt', 'Garden City'],
  ['NEON', 'Wyatt', 'Garden City'],
  ['Wiley Records', 'Wyatt', 'Garden City'],
  ['GC Library/City Hall', 'Wyatt', 'Garden City'],
  ['Goldsteins', 'Tori', 'Downtown Capital to 9th'],
  ['White dog', 'Tori', 'Downtown Capital to 9th'],
  ['Alpha graphics', 'Tori', 'Downtown Capital to 9th'],
  ['Idaho Candy Co', 'Tori', 'Downtown Capital to 9th'],
  ['Treefort office (x20)', 'Tori', 'Downtown Capital to 9th'],
  ['Acero', 'Tori', 'Downtown Capital to 9th'],
  ['Chocolat bar', 'Tori', 'Downtown Capital to 9th'],
  ['Cotopaxi', 'Tori', 'Downtown Capital to 9th'],
  ['Rediscovered books', 'Tori', 'Downtown Capital to 9th'],
  ['Diablo and Sons', 'Tori', 'Downtown Capital to 9th'],
  ['Pie hole', 'Tori', 'Downtown Capital to 9th'],
  ['Bittercreek', 'Tori', 'Downtown Capital to 9th'],
  ['Prost', 'Tori', 'Downtown Capital to 9th'],
  ['Zeppole', 'Tori', 'Downtown Capital to 9th'],
  ['Dawson Taylor', 'Tori', 'Downtown Capital to 9th'],
  ['10 barrel', 'Tori', 'Downtown Capital to 9th'],
  ['Funky Taco', 'Tori', 'Downtown Capital to 9th'],
  ['Flying M', 'Tori', 'Nampa'],
  ['Whiskey River', 'Tori', 'Nampa'],
  ['The Stil', 'Tori', 'Nampa'],
  ['Mesa Tacos', 'Tori', 'Nampa'],
  ['Pre-funk (x2)', 'Tori', 'Nampa'],
  ["TK's", 'Jim', 'Federal Way'],
  ['The Stil', 'Jim', 'Harris Ranch'],
  ['Sushi Shack', 'Jim', 'Harris Ranch'],
  ['Boise Fry Co', 'Jim', 'Harris Ranch'],
  ['Lucky 13', 'Jim', 'Harris Ranch'],
  ['The Barrio', 'Jim', 'Bown Crossing'],
  ['Ti Amo', 'Jim', 'Bown Crossing'],
  ['Nara Ramen', 'Jim', 'Bown Crossing'],
  ["Sid's Garage", 'Jim', 'Bown Crossing'],
  ['The Refuge', 'Jim', 'Park Center'],
  ['Smokey Mountain', 'Jim', 'Broadway'],
  ['M and W', 'Jim', 'Warm Springs'],
  ['Tin Roof Tacos', 'Jim', 'Broadway'],
  ['Uptown Cheapskate', 'Jim', 'Broadway'],
  ['End Zone', 'Jim', 'Broadway'],
  ['Suds', 'Jim', 'Broadway'],
  ['Pie Hole', 'Jim', 'Broadway'],
  ['Boulder Barber', 'Jim', 'Broadway'],
  ['The James', 'Jim', 'Broadway'],
  ['Burger Belly', 'Jim', 'Broadway'],
  ['R Bar', 'Jim', 'Broadway'],
  ['Eastside Tavern', 'Jim', 'Broadway'],
  ['Big Juds', 'Jim', 'Broadway'],
  ['Broadway on the Rocks', 'Jim', 'Broadway'],
  ['Jersey Mikes', 'Jim', 'Broadway'],
  ['Idaho Pizza Company', 'Jim', 'Broadway'],
  ['Pyramid Tattoo', 'Jim', 'Broadway'],
  ['Broadway Bar', 'Jim', 'Broadway'],
  ['Play It Again Sports', 'Jim', 'Broadway'],
  ['Syubs', 'Jim', 'Broadway'],
  ["Jim's Alibi", 'Jim', 'Broadway'],
  ['Six Daggers Tattoo', 'Jim', 'Broadway'],
  ['Flying Pie', 'Jim', 'Broadway'],
  ['HillTop', 'Jim', 'Highway 21'],
  ['Hi Tech Printers', 'Casey', 'Downtown 9th to 15th'],
  ['Iron Wolf', 'Casey', 'Downtown 9th to 15th'],
  ['Foot Dynamics', 'Casey', 'Downtown 9th to 15th'],
  ['Boise Bodega', 'Casey', 'Downtown 9th to 15th'],
  ['The Sparrow', 'Casey', 'Downtown 9th to 15th'],
  ['Mulligans', 'Casey', 'Downtown 9th to 15th'],
  ['The Modern', 'Casey', 'Downtown 9th to 15th'],
  ['Hops and Bottles', 'Casey', 'Downtown 9th to 15th'],
  ['Crazy Neighbor', 'Casey', 'Downtown 9th to 15th'],
  ['Outdoor Exchange', 'Casey', 'Downtown 9th to 15th'],
  ['Neurolux', 'Casey', 'Downtown 9th to 15th'],
  ['Record Exchange (8)', 'Casey', 'Downtown 9th to 15th'],
  ['Shriner', 'Casey', 'Downtown 9th to 15th'],
  ['Barbarian DT', 'Casey', 'Downtown 9th to 15th'],
  ['Inkslaves Tattoo', 'Casey', 'Downtown 9th to 15th'],
  ['10th Street Station', 'Casey', 'Downtown 9th to 15th'],
  ['Boise Barber', 'Casey', 'Downtown 9th to 15th'],
  ['Guru Donuts', 'Casey', 'Downtown 9th to 15th'],
  ["Alia's", 'Casey', 'Downtown 9th to 15th'],
  ['LemonTree', 'Casey', 'Downtown 9th to 15th'],
  ['The District', 'Casey', 'Downtown 9th to 15th'],
  ['Big O Tires', 'Casey', 'Downtown 9th to 15th'],
  ['Matlacks', 'Casey', 'Downtown 9th to 15th'],
  ['Anthonys', 'Casey', 'Downtown 9th to 15th'],
  ['JUMP', 'Casey', 'Downtown 9th to 15th'],
  ['Boise Art Glass', 'Casey', 'Downtown 9th to 15th'],
  ['Black Rose Tattoo', 'Casey', 'Downtown 9th to 15th'],
  ['Belmont Barber', 'Casey', 'Downtown 9th to 15th'],
  ['Don and Charleys', 'Casey', 'Downtown 9th to 15th'],
  ['Ginza Sushi', 'Casey', 'Downtown 9th to 15th'],
  ['Paddles Up Poke', 'Casey', 'Downtown 9th to 15th'],
  ['Spitfire Pizza', 'Jake', 'Vista'],
  ['Brewers Haven', 'Jake', 'Vista'],
  ['Albertsons Vista', 'Jake', 'Vista'],
  ['Red Bench', 'Jake', 'Vista'],
  ['Chapala', 'Jake', 'Vista'],
  ['Ophidia', 'Jake', 'Vista'],
  ['Rizzo', 'Jake', 'Vista'],
  ['Sakana', 'Jake', 'Vista'],
  ['Bark and Purr', 'Jake', 'Vista'],
  ['Ceramica', 'Jake', 'Vista'],
  ['BBQ 4 Life', 'Jake', 'Vista'],
  ['Vista Bar', 'Jake', 'Vista'],
  ['Restyle', 'Jake', 'Vista'],
  ['Modern Vinyl', 'Jake', 'Vista'],
  ["Here's How (old Janets)", 'Jake', 'Vista'],
  ['Primal Coffee', 'Jake', 'Latah'],
  ['Stil Latah', 'Jake', 'Latah'],
  ['Push and Pour Latah', 'Jake', 'Latah'],
  ['Navajo', 'Jake', 'Orchard'],
  ['Lark and Larder', 'Jake', 'Orchard'],
  ['Das Alpenhaus', 'Jake', 'Vista'],
  ['Bikes and Beans', 'Jake', 'Vista'],
  ['Lulus Pizza', 'Justin', 'Bogus Basin'],
  ['Timber Coffee', 'Justin', 'Bogus Basin'],
  ['Eco Lounge', 'Justin', 'Bogus Basin'],
  ['Highlands Hollow', 'Justin', 'Bogus Basin'],
  ["O'Michael's", 'Justin', 'Bogus Basin'],
  ['Ski Haus', 'Justin', 'Bogus Basin'],
  ['Indy Clover', 'Justin', 'State Street'],
  ['Mazzah', 'Justin', 'State Street'],
  ['Cloud 9', 'Justin', 'State Street'],
  ['Rush Bowls', 'Justin', 'State Street'],
  ['Dutch Bros 16th and State', 'Justin', 'State Street'],
  ['Fanci Freeze', 'Justin', 'State Street'],
  ['Dharma', 'Madi', 'Downtown 4th to Capital'],
  ['Java', 'Madi', 'Downtown 4th to Capital'],
  ['Bar Please', 'Madi', 'Downtown 4th to Capital'],
  ['Seoul Cafe', 'Madi', 'Downtown 4th to Capital'],
  ['Boise Fry Co DT', 'Madi', 'Downtown 4th to Capital'],
  ["JD's Bodega", 'Madi', 'Downtown 4th to Capital'],
  ['Egyptian', 'Madi', 'Downtown 4th to Capital'],
  ["Goldy's Corner", 'Madi', 'Downtown 4th to Capital'],
  ['Basque Center', 'Madi', 'Downtown 4th to Capital'],
  ['Bardenay', 'Madi', 'Downtown 4th to Capital'],
  ['Silly Birch', 'Madi', 'Downtown 4th to Capital'],
  ['Jimmy Johns DT', 'Madi', 'Downtown 4th to Capital'],
  ["Penguilly's", 'Madi', 'Downtown 4th to Capital'],
  ['Ochos', 'Madi', 'Downtown 4th to Capital'],
  ['Reef', 'Madi', 'Downtown 4th to Capital'],
  ['Graineys', 'Madi', 'Downtown 4th to Capital'],
  ['Leku Ona', 'Madi', 'Downtown 4th to Capital'],
  ["Hannah's", 'Madi', 'Downtown 4th to Capital'],
  ['Press and Pony', 'Madi', 'Downtown 4th to Capital'],
  ['Guidos', 'Madi', 'Downtown 4th to Capital'],
  ['HIgh Note Cafe', 'Madi', 'Downtown 4th to Capital'],
  ['Blue Sky Bagels DT', 'Madi', 'Downtown 4th to Capital'],
  ['Form and Function DT', 'Madi', 'Downtown 4th to Capital'],
  ['Mod Pizza', 'Madi', 'Downtown 4th to Capital'],
  ['Yoi Tomo', 'Madi', 'BoDo'],
  ['Solid', 'Madi', 'BoDo'],
  ['El Tejano', 'Madi', 'BoDo'],
  ['Liquid', 'Madi', 'BoDo'],
  ['Slow by Slow', 'Madi', 'BoDo'],
  ['Kichi', 'Madi', 'Downtown 4th to Capital'],
  ['White Dog Brewing', 'Madi', 'Downtown 4th to Capital'],
  ['Nomad', 'Madi', 'Downtown 4th to Capital'],
  ['Gas Lantern', 'Madi', 'Downtown 4th to Capital'],
  ["Goldy's", 'Madi', 'Downtown 4th to Capital'],
  ['Parilla HP', 'Justin', 'Hyde Park'],
  ['13th St Pub', 'Justin', 'Hyde Park'],
  ['Lost Grove HP', 'Justin', 'Hyde Park'],
  ['Java HP', 'Justin', 'Hyde Park'],
  ['Tri-Town Bicycles', 'Justin', 'Hyde Park'],
  ['North End Pizza', 'Justin', 'Hyde Park'],
  ['Hyde Perk', 'Justin', 'Hyde Park'],
  ['Hyde Park Pub and Grill', 'Justin', 'Hyde Park']
]

assignments.each do |business_name, user_first_name, area|
  user = User.find_by(first_name: user_first_name)
  if user
    Assignment.create!(
      user_id: user.id,
      business_name: business_name,
      area: area,
      wave_one: false,
      wave_two: true,
      wave_three: false,
      other: false,
      notes: ''
    )
  else
    puts "User with first name #{user_first_name} not found. Skipping assignment for #{business_name}."
  end
end
